### ISSUE TITLE
Events & Commands 

### ISSUE THREAD

**Issue by neonboxx** [Sequensis/sequensis.github.io#1]
Add a brief description of each and an example of when we use events and when we use commands

**Comment by wordshaker** [comment]
I'll jump on this

**Comment by luap** [comment]
Also interested in this one!

**Comment by wordshaker** [comment]
Want to work together? We can pair

**Comment by neonboxx** [comment]
Please feel free to add issues for any other patterns/practices we use.

**Comment by wordshaker** [comment]
I will back off from this and pass of to Matt Whetton

**Comment by wordshaker** [comment]
Please see @mattwhetton's PR [here](https://github.com/Sequensis/sequensis.github.io/pull/19)

**Comment by neonboxx** [comment]
I'm closing this, if anyone wants to add more they can open a new issue #19
