### ISSUE TITLE
Data Access Patterns

### ISSUE THREAD

**Issue by wordshaker** [Sequensis/sequensis.github.io#16]
How we store, access, examine data stores in our system

- Repository patterns and alternative patterns
- Whats good or whats not
- What we should be using consisently
- How to do it

**Comment by Supercide** [comment]
Repository pattern is great for controlling what operations are allowed when working with persistence. for example you can lock down if a customer can ever be deleted from the system, this is great for when you need to protect domain invariants

**Comment by luap** [comment]
@Supercide is that you volunteering to pick up this item?!
